.PHONY: clean All

All:
	@echo "----------Building project:[ pointerArithmetic3 - Debug ]----------"
	@cd "pointerArithmetic3" && "$(MAKE)" -f  "pointerArithmetic3.mk"
clean:
	@echo "----------Cleaning project:[ pointerArithmetic3 - Debug ]----------"
	@cd "pointerArithmetic3" && "$(MAKE)" -f  "pointerArithmetic3.mk" clean
